In [23]:
import numpy as np

print('\n1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.')
a1 = np.arange(1, 10+1, 1, dtype=int)
print(a1)

print('\n2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.')
m1 = np.zeros((3,3), dtype=int)
print(m1)

print('\n3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.')
m2 = np.random.randint(1, 10, (5,5))
print(m2)

print('\n4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.')
m3 = np.random.uniform(0, 1, (4,4))
print(m3)

print('\n5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.')
a2 = np.random.randint(1, 10, 5)
a3 = np.random.randint(1, 10, 5)
print(f"Array 1: {a2}, Array 2: {a3}")
print(f"Add: {a2+a3}, Sub: {a2-a3}, Mul: {a2*a3}")

print('\n6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.')
a4 = np.random.randint(1, 100, 7)
a5 = np.random.randint(1, 100, 7)
s1 = np.dot(a4, a5)
print(f"Vector1:{a4}, Vector 2:{a5}, Scalar:{s1}")

print('\n7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.')
m4 = np.random.randint(1, 10, (2,2))
m5 = np.random.randint(1, 10, (2,3))
m6 = np.dot(m4,m5)
print(f"Matrix 1:\n{m4}\n Matrix 2:\n{m5}\n Matrix result:\n{m6}")

print('\n8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.')
m7 = np.random.randint(1, 10, (3,3))
m7_inv = np.linalg.inv(m7)
print(f"Matrix:\n{m7}\n Inv Matrix\n{m7_inv}")

print('\n9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.')
m8 = np.random.uniform(0, 1, (4,4))
m9 = m8.T
print(f"Matrix:\n{m8}\nMatrix T:\n{m9}")

print('\n10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.')
m10 = np.random.randint(1, 10, (3,4))
a6 = np.random.randint(1, 10, 4)
m11 = m10*a6
print(f"Matrix:\n{m10}\nVector:\n{a6}\nResult:\n{m11}")

print('\n11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.')
m11 = np.random.uniform(0, 1, (2,3))
a7 = np.random.uniform(0, 1, 3)
m12 = m11*a7
print(f"Matrix:\n{m11}\nVector:\n{a7}\nResult:\n{m12}")

print('\n12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.')
m13 = np.random.randint(1, 10, (2,2))
m14 = np.random.randint(1, 10, (2,2))
m15 = m13*m14
print(f"Matrix 1:\n{m13}\nMatrix 2:\n{m14}\nResult:\n{m15}")

print('\n13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.')
m16 = np.random.randint(1, 10, (2,2))
m17 = np.random.randint(1, 10, (2,2))
s2 = np.dot(m16, m17)
print(f"Matrix 1:\n{m16}\nMatrix 2:\n{m17}\nResult:\n{s2}")

print('\n14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.')
m19 = np.random.randint(1, 100, (5,5))
s3 = m19.sum()
print(f"Matrix :\n{m19}\nMatrix elements sum:{s3}")

print('\n15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.')
m22 = np.random.randint(1, 10, (4,4))
m23 = np.random.randint(1, 10, (4,4))
m24 = m22-m23
print(f"Matrix 1:\n{m22}\nMatrix 2:\n{m23}\nResult M1-M2:\n{m24}")

print('\n16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.')
m25 = np.random.uniform(0, 1, (3,3))
m26 = np.sum(m25, axis=1)
m26_T = np.array([m26]).T
print(f"Matrix:\n{m25}\nVector:\n{m26_T}")

print('\n17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.')
m27 = np.random.randint(1, 10, (3,3))
m28 = m27*m27
print(f"Matrix initial:\n{m27}\nMatrix power2:\n{m28}")

print('\n18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.')
a8 = np.random.randint(1, 50, 4)
a8_sqrt = np.sqrt(a8)
print(f"Vector initial:{a8}\nVector sqrt:{a8_sqrt}")


1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
[ 1  2  3  4  5  6  7  8  9 10]

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
[[0 0 0]
 [0 0 0]
 [0 0 0]]

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
[[1 5 9 5 3]
 [5 9 7 1 9]
 [7 9 6 6 4]
 [4 5 4 8 2]
 [1 3 2 1 1]]

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
[[0.55669655 0.29199993 0.64180119 0.29762464]
 [0.08001859 0.23769133 0.12633943 0.41733837]
 [0.86801416 0.70493827 0.13317661 0.61200038]
 [0.09883784 0.02348534 0.26437756 0.60197632]]

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.
Array 1: [9 7 3 7 6], Array 2: [3 